// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9SIe3eKvdkI7qhW4zH96NDHNomMOlQz4',
    appId: '1:733169150206:android:a35558085a447753271daf',
    messagingSenderId: '733169150206',
    projectId: 'techlibrary-5488a',
    databaseURL: 'https://techlibrary-5488a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techlibrary-5488a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBo0AfrLI6bCc77k6h_YsL-e16GMskNnA',
    appId: '1:733169150206:ios:9887e42b8a5d999d271daf',
    messagingSenderId: '733169150206',
    projectId: 'techlibrary-5488a',
    databaseURL: 'https://techlibrary-5488a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techlibrary-5488a.appspot.com',
    iosClientId: '733169150206-6u1j2413i637gham1o6pfva8oflnp0ne.apps.googleusercontent.com',
    iosBundleId: 'techLibrary',
  );
}
